
# Site settings
title: Operation Zombie
email: outleveledgames@gmail.com
url: https://ronaldt-git.github.io
description: "Download Operation Zombie On the App Store or Google Play today. A Top-Down zombie shooter with endless rounds."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Outleveled Games

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Outleveled/
  - title: instagram
    url: https://www.instagram.com/outleveledgames/
  - title: linkedin
    url: https://www.linkedin.com/in/ronald-tourtellot-4535b1170/
  - title: chrome-web-store
    url: https://chromewebstore.google.com/detail/steady-linguist/lcbiohoeaneglegahhhfkmcfpplhamck

# Build settings
markdown: kramdown
permalink: pretty
